import json

from snakemake.utils import min_version

min_version('8.11')


with open('config/config.json', 'r') as f:
    cfg = json.load(f)


# TODO: 
# - SNP-level comparisons
# - sequence typing


module infant_mbiome:
    snakefile: '/viper/ptmp/thosi/wv-multilib/workflow/Snakefile'
    config: config


use rule * from infant_mbiome as bb_*


rule all:
    input:
        'aggregated.txt'
    default_target: True


checkpoint get_legacy_snps:
    output:
        directory('resources/legacy_snps')
    params:
        path=cfg['legacy_snps_path']
    resources:
        njobs=20,
        slurm_partition='datatransfer'
    envmodules:
        'rclone/1.67.0'
    shell:
        'rclone copy "nextcloud:{params.path}" {output}'


def aggregate_legacy_snps(wildcards):
    import os
    checkpoint_output = checkpoints.get_legacy_snps.get(**wildcards).output[0]
    snps, = glob_wildcards(os.path.join(checkpoint_output, "{snp}.tree"))
    return expand("resources/legacy_snps/{snp}.tree", snp=snps)


rule:
    input:
        aggregate_legacy_snps
    output:
        'aggregated.txt'
    shell:
        'cat {input} > {output}'